dying subjobs on server restart due to incorect qrank type

diff --git a/src/cmds/scripts/pbs_schema_upgrade b/src/cmds/scripts/pbs_schema_upgrade
--- a/src/cmds/scripts/pbs_schema_upgrade
+++ b/src/cmds/scripts/pbs_schema_upgrade
@@ -247,10 +247,24 @@ upgrade_pbs_schema_from_v1_3_0() {
 	fi
 }
 
+upgrade_pbs_schema_from_v1_4_0() {
+
+	${PGSQL_DIR}/bin/psql -p ${PBS_DATA_SERVICE_PORT} -d pbs_datastore -U ${PBS_DATA_SERVICE_USER} <<-EOF > /dev/null
+		ALTER TABLE pbs.job ALTER COLUMN ji_qrank TYPE BIGINT;
+		UPDATE pbs.info SET pbs_schema_version = '1.4.1';
+	EOF
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		echo "Some datastore transformations failed to complete"
+		echo "Please check dataservice logs"
+		return $ret
+	fi
+}
+
 # start of the upgrade schema script
 
 tmpdir=${PBS_TMPDIR:-${TMPDIR:-"/var/tmp"}}
-PBS_CURRENT_SCHEMA_VER='1.4.0'
+PBS_CURRENT_SCHEMA_VER='1.4.1'
 conf=${PBS_CONF_FILE:-/etc/pbs.conf}
 PBS_DATA_SERVICE_PORT="$1"
 PBS_DATA_SERVICE_USER="$2"
@@ -362,6 +376,15 @@ if [ "$ver" = "1.3.0" ]; then
         exit $ret
     fi
     ver="1.4.0"
+fi
+
+if [ "$ver" = "1.4.0" ]; then
+    upgrade_pbs_schema_from_v1_4_0
+    ret=$?
+    if [ $ret -ne 0 ]; then
+        exit $ret
+    fi
+    ver="1.4.1"
 else
     echo "Cannot upgrade PBS datastore version $ver"
     ret=$?
